const marcas = [
    "Agrale",
    "Aston Martin",
    "Audi",
    "Bentley",
    "BMW",
    "BYD",
    "CAOA Chery",
    "Chevrolet",
    "Citroën",
    "Denza",
    "Effa",
    "Ferrari",
    "Fiat",
    "Ford",
    "Foton",
    "GAC",
    "Geely",
    "GWM",
    "Honda",
    "Hyundai",
    "Iveco",
    "JAC Motors",
    "Jaecoo",
    "Jaguar",
    "Jeep",
    "Jetour",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Leapmotor",
    "Lexus",
    "Maserati",
    "McLaren",
    "Mercedes-AMG",
    "Mercedes-Benz",
    "MG",
    "Mini",
    "Mitsubishi",
    "Nissan",
    "Peugeot",
    "Porsche",
    "RAM",
    "Renault",
    "Subaru",
    "Suzuki",
    "Toyota",
    "Troller",
    "Volkswagen",
    "Volvo"
]

export default marcas